PARK_FACTORS_HR = {
    "COL": 1.30,
    "CIN": 1.15,
    "TEX": 1.12,
    "PHI": 1.10,
    "BAL": 1.08,
    "BOS": 1.05,
    "NYY": 1.04,
    "MIL": 1.03,
    "ATL": 1.02,
    "HOU": 1.01,
    "ARI": 1.00,
    "LAA": 0.99,
    "DET": 0.98,
    "MIN": 0.97,
    "CLE": 0.96,
    "WSH": 0.95,
    "CHC": 0.95,
    "TOR": 0.94,
    "STL": 0.94,
    "KC": 0.93,
    "NYM": 0.93,
    "PIT": 0.92,
    "MIA": 0.92,
    "TB": 0.91,
    "LAD": 0.91,
    "CHW": 0.90,
    "SD": 0.90,
    "SEA": 0.89,
    "OAK": 0.88,
    "SF": 0.77,
}

PA_COLS = [
    "game_date",
    "batter",
    "pitcher",
    "stand",
    "p_throws",
    "events",
    "home_team",
    "away_team",
    "inning",
    "inning_topbot",
    "outs_when_up",
    "on_1b",
    "on_2b",
    "on_3b",
    "balls",
    "strikes",
    "bat_score",
    "fld_score",
    "launch_speed",
    "estimated_woba_using_speedangle",
    "game_pk",
    "at_bat_number",
]

OUTCOMES = [
    "1B",
    "2B",
    "3B",
    "HR",
    "BB",
    "SO",
    "HBP",
    "GDP",
    "SF",
    "OUT",
]

OUTCOME_MAP = {
    "single": "1B",
    "double": "2B",
    "triple": "3B",
    "home_run": "HR",
    "walk": "BB",
    "intentional_walk": "BB",
    "strikeout": "SO",
    "strikeout_double_play": "SO",
    "hit_by_pitch": "HBP",
    "grounded_into_double_play": "GDP",
    "sac_fly": "SF",
}
